### ISSUE TITLE
Could not execute entrypoint stage 'main' due to errors, provided by 'queen-cats'

### ISSUE THREAD

**Issue by jwols123** [RonaldCabrera/Queen-Cats-Dogs-Fabric#2]
When loading Queen Cats and Dogs Fabric 1.20.1 the game fails to load with the most notable error being:
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'queen-cats' at 'net.pevori.queencats.QueenCats'!
In a modpack with only it and its dependencies, it still crashes (as seen in the log below)
I have tried changing the version of the fabric loader (not the game loader), but it still crashes.
https://pastebin.com/Sm3swTaH
(note: every instance of the actual system name has been replaced with "SYSTEMNAME")

**Comment by jwols123** [comment]
1.18.2 Fabric also seems to have the same crash.
1.18.2 Forge seems to load fine as I load in and can use the mod fine.
Seems to be fabric in general that's broken.

**Comment by RonaldCabrera** [comment]
You forgot to install MidnightLib, it's a required dependency.

**Comment by jwols123** [comment]
Just a heads up, it says nothing about requiring Midnight Lib. It says it requires GeckoLib but nothing about MidnightLib.
https://modrinth.com/mod/queen-cats-dogs
I don't see anything about MidnightLib on this page.

**Comment by RonaldCabrera** [comment]
It was added on the version as a requirement, it should download automatically when using the Modrinth App, although it's true it was not specified in the mod page itself, added, thanks for pointing it out.
